### ISSUE TITLE
Deux mots

### ISSUE THREAD

**Issue by maelle** [fmichonneau/datacarpentry-organization-translations#1]
* Pour "héberger" je me demande si "accueillir" serait mieux ?

* Pour "instructeur", je pense entendre plus souvent "formateur" en français, est-ce que cela te va si je change ?

**Comment by fmichonneau** [comment]
Oui je pense que tes suggestions sont mieux. Qu'est ce que tu penses de "workshop"? Au début je l'avais laissé tel quel, mais après je me suis dit que "atelier" était mieux...

**Comment by maelle** [comment]
Oui du coup j'ai même changé tous les workshops restants en ateliers. :wink: Je vais faire les changements !

**Comment by fmichonneau** [comment]
OK, merci bien ! je vais essayer de continuer à traduire dans la journée.

**Comment by maelle** [comment]
Parfait et je relirai à l'occasion, merci beaucoup pour ton travail ! J'espère que tout ceci sera utile. :grin:
